import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderGlobal from "@/components/layout/HeaderGlobal";
import GNB from "@/components/layout/GNB";
import FooterGlobal from "@/components/layout/FooterGlobal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full"><body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen pt-[6.5rem]`}
      >
        <HeaderGlobal />
        <GNB />
        <main className="flex-grow">
          {children}
        </main>
        <FooterGlobal />
      </body></html>
  );
}
