import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderGlobal from "@/components/layout/HeaderGlobal";
import GNB from "@/components/layout/GNB";
import FooterGlobal from "@/components/layout/FooterGlobal"; // Added FooterGlobal import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full"><body // <--- <html>과 <body>를 같은 줄에 붙임
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen pt-[6.5rem]`} // Adjusted for sticky footer
      >
        <HeaderGlobal />
        <GNB />
        <main className="flex-grow"> {/* Added main tag with flex-grow */}
          {children}
        </main>
        <FooterGlobal /> {/* Added FooterGlobal component */}
      </body></html> // <--- </body>와 </html>을 같은 줄에 붙임
  );
}
